-- Only the test copy. This is intentionally not an automatic Laravel migration.
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
IF ISNULL(CONVERT(int, SERVERPROPERTY('IsLocalDB')), 0) <> 1 OR DB_NAME() <> N'IPS5Db'
    THROW 51000, 'This script only supports the IPS5Db LocalDB test copy.', 1;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.L_MAILITM_EVENTS') AND name = N'IX_SITRA_MAILITM_EVENTS_LATEST')
BEGIN
    CREATE NONCLUSTERED INDEX IX_SITRA_MAILITM_EVENTS_LATEST
    ON dbo.L_MAILITM_EVENTS (MAILITM_PID, EVENT_GMT_DT DESC, EVENT_TYPE_CD DESC)
    INCLUDE (EVENT_OFFICE_CD, NEXT_OFFICE_CD)
    WITH (MAXDOP = 2);
END;

SELECT name, is_disabled FROM sys.indexes
WHERE object_id = OBJECT_ID(N'dbo.L_MAILITM_EVENTS') AND name = N'IX_SITRA_MAILITM_EVENTS_LATEST';
-- Optional rollback after checking the same server/database guard:
-- DROP INDEX IX_SITRA_MAILITM_EVENTS_LATEST ON dbo.L_MAILITM_EVENTS;
