@php($fields = $declaration['data']['fields'])
@php($countries = $declaration['countries'] ?? [])
<article class="postal-declaration">
    <div class="postal-section-heading"><h3>Declaración aduanera</h3><span class="postal-source">{{ $declaration['state'] ?? 'Estado no informado' }}</span></div>
    <p class="postal-note">ID {{ $declaration['id'] }} · Paquete interno {{ $declaration['package_id'] }}</p>
    @if($declaration['data']['status'] !== 'ok')<div class="alert alert-warning">El contenido de esta declaración está vacío o no pudo interpretarse. No se ha completado con datos supuestos.</div>@endif
    <div class="postal-contact-grid"><div><span class="postal-eyebrow">REMITENTE DECLARADO</span><h3>{{ $fields['SNm'] ?? 'No informado' }}</h3><p>{{ $fields['SAdL1'] ?? '' }} {{ $fields['SAdL2'] ?? '' }}</p><p>{{ $fields['SCty'] ?? '' }} {{ $fields['SZip'] ?? '' }} · {{ $countries[$fields['SCtr'] ?? ''] ?? $fields['SCtr'] ?? 'País no informado' }}</p></div><div><span class="postal-eyebrow">DESTINATARIO DECLARADO</span><h3>{{ $fields['RNm'] ?? 'No informado' }}</h3><p>{{ $fields['RAdL1'] ?? '' }} {{ $fields['RAdL2'] ?? '' }}</p><p>{{ $fields['RCty'] ?? '' }} {{ $fields['RZip'] ?? '' }} · {{ $countries[$fields['RCtr'] ?? ''] ?? $fields['RCtr'] ?? 'País no informado' }}</p></div></div>
    <div class="postal-facts"><div><span>Peso bruto declarado</span><strong>{{ $fields['GWgt'] ?? 'No informado' }}</strong></div><div><span>Valor declarado</span><strong>{{ $fields['TotCPVal'] ?? 'No informado' }} {{ $fields['TotalCPValCur'] ?? '' }}</strong></div><div><span>Naturaleza del contenido</span><strong>{{ $declaration['nature'] ?? $fields['NTypDesc'] ?? $fields['NTyp'] ?? 'No informada' }}</strong></div></div>
    <div class="table-responsive"><table class="table"><thead><tr><th>Artículo declarado</th><th>Unidades</th><th>Valor / moneda</th><th>Peso neto</th><th>País de fabricación</th></tr></thead><tbody>@forelse($declaration['data']['pieces'] as $piece)<tr><td>{{ $piece['Desc'] ?? 'Sin descripción' }}</td><td>{{ $piece['No'] ?? '—' }}</td><td>{{ $piece['Amt'] ?? '—' }} {{ $piece['Cur'] ?? '' }}</td><td>{{ $piece['NWgt'] ?? '—' }}</td><td>{{ $countries[$piece['OCtr'] ?? ''] ?? $piece['OCtr'] ?? '—' }}</td></tr>@empty<tr><td colspan="5">Sin artículos detallados.</td></tr>@endforelse</tbody></table></div>
    @if(!empty($fields['Obs']))<p><strong>Observaciones:</strong> {{ $fields['Obs'] }}</p>@endif
    @if($declaration['data']['documents'])<details><summary>Documentos declarados ({{ count($declaration['data']['documents']) }})</summary>@foreach($declaration['data']['documents'] as $document)<p><strong>{{ $document['type'] }}</strong>@foreach($document['fields'] as $key=>$value) · {{ $key }}: {{ $value }}@endforeach</p>@endforeach</details>@endif
    <details><summary>Campos de origen de CDS</summary><dl>@foreach($fields as $key=>$value)<dt>{{ $key }}</dt><dd>{{ $value }}</dd>@endforeach</dl>@foreach($declaration['data']['pieces'] as $piece)<h4>Artículo {{ $loop->iteration }}</h4><dl>@foreach($piece as $key=>$value)<dt>{{ $key }}</dt><dd>{{ $value }}</dd>@endforeach</dl>@endforeach</details>
</article>
