<div class="postal-workspace">
    <section class="postal-hero"><div><span class="postal-eyebrow">INFORMACIÓN POSTAL CONECTADA</span><h2>Todo comienza con<br>el código del paquete.</h2><p>IPS para su recorrido. CDS para su declaración aduanera.<br>Información identificada por fuente y responsable.</p></div><i class="fas fa-box-open postal-hero-icon" aria-hidden="true"></i></section>
    @can('postal.access')<form class="postal-search" method="get" action="{{ route('consultas.index') }}"><label for="home-code">Buscar un envío</label><div class="postal-search-row"><i class="fas fa-barcode" aria-hidden="true"></i><input id="home-code" name="codigo" maxlength="35" placeholder="Código S10 o identificador local" required><button class="btn btn-primary">Abrir expediente <i class="fas fa-arrow-right"></i></button></div></form>@endcan
    <div class="postal-task-grid">
        @can('postal.ips')<a class="postal-task" href="{{ route('postal.ips') }}"><span class="postal-task-icon"><i class="fas fa-globe-americas"></i></span><h2>Consulta IPS</h2><p>Paquetes, movimientos, operadores y despachos.</p><strong>Buscar paquete <i class="fas fa-arrow-right"></i></strong></a>@endcan
        @can('postal.ips')<a class="postal-task" href="{{ route('postal.receptacles') }}"><span class="postal-task-icon gold"><i class="fas fa-barcode"></i></span><h2>Marbetes y sacas</h2><p>Encuentra el receptáculo y revisa sus paquetes asociados.</p><strong>Buscar marbete <i class="fas fa-arrow-right"></i></strong></a>@endcan
        @can('postal.cds')<a class="postal-task" href="{{ route('postal.cds') }}"><span class="postal-task-icon teal"><i class="fas fa-clipboard-list"></i></span><h2>Consulta CDS</h2><p>Declaraciones, artículos, decisiones y responsables.</p><strong>Buscar declaración <i class="fas fa-arrow-right"></i></strong></a>@endcan
        @can('postal.access')<a class="postal-task" href="{{ route('postal.combined') }}"><span class="postal-task-icon"><i class="fas fa-project-diagram"></i></span><h2>IPS + CDS</h2><p>Compara el recorrido del paquete con el registro aduanero.</p><strong>Abrir búsqueda conjunta <i class="fas fa-arrow-right"></i></strong></a>@endcan
        @can('ips.read')<a class="postal-task" href="{{ route('operaciones.index') }}"><span class="postal-task-icon gold"><i class="fas fa-boxes"></i></span><h2>Paquetes y entregas</h2><p>Gestiona los movimientos de IPS con los permisos de tu cuenta.</p><strong>Abrir operaciones <i class="fas fa-arrow-right"></i></strong></a>@endcan
        @can('admin-only')<a class="postal-task" href="{{ route('postal.access.index') }}"><span class="postal-task-icon"><i class="fas fa-user-shield"></i></span><h2>Accesos del equipo</h2><p>Controla quién puede consultar y quién puede registrar operaciones.</p><strong>Administrar permisos <i class="fas fa-arrow-right"></i></strong></a>@endcan
    </div>
</div>
