@extends('adminlte::page')
@section('title', $sectionTitle.' | SITRA')
@section('content_header')
    <div class="postal-heading"><div><span class="postal-eyebrow">SITRA · CONSULTA POSTAL</span><h1>{{ $sectionTitle }}</h1><p>{{ $sectionDescription }}</p></div><span class="postal-source"><i class="fas fa-shield-alt" aria-hidden="true"></i> Consulta interna</span></div>
@stop
@section('content')
<div class="postal-workspace">
    <nav class="postal-tabs postal-section-nav" aria-label="Consultas postales">
        @can('postal.ips')<a @if($section==='ips')aria-current="page"@endif href="{{ route('postal.ips',['codigo'=>$code ?: null]) }}"><i class="fas fa-globe-americas"></i> IPS</a><a href="{{ route('postal.receptacles') }}"><i class="fas fa-barcode"></i> Marbetes</a>@endcan
        @can('postal.cds')<a @if($section==='cds')aria-current="page"@endif href="{{ route('postal.cds',['codigo'=>$code ?: null]) }}"><i class="fas fa-clipboard-list"></i> CDS</a>@endcan
        @can('postal.access')<a @if($section==='conjunto')aria-current="page"@endif href="{{ route('postal.combined',['codigo'=>$code ?: null]) }}"><i class="fas fa-project-diagram"></i> IPS + CDS</a>@endcan
    </nav>
    <form class="postal-search" action="{{ $searchRoute }}" method="get">
        <label for="postal-code">Código S10 o identificador local</label>
        <div class="postal-search-row"><i class="fas fa-barcode" aria-hidden="true"></i><input id="postal-code" name="codigo" value="{{ $code }}" maxlength="35" required autocomplete="off" placeholder="Escanea o escribe el código del paquete"><button class="btn btn-primary"><i class="fas fa-search" aria-hidden="true"></i> Buscar en {{ $searchTarget }}</button></div>
        @error('codigo')<p class="text-danger">{{ $message }}</p>@enderror
    </form>
    <div class="postal-sources" role="status">
        @foreach($sources as $source => $state)
            <div class="postal-source {{ $state === 'unavailable' ? 'postal-warning' : '' }}"><span class="postal-dot {{ $state === 'ok' ? 'is-ready' : '' }}"></span><strong>{{ $source }}</strong><span>{{ $sourceLabels[$state] }}</span></div>
        @endforeach
    </div>
    @if(!$code)
        <div class="postal-empty"><i class="fas fa-box-open" aria-hidden="true"></i><h2>Comienza con el código del envío</h2><p>Podrás revisar su recorrido, artículos declarados, documentos y responsables registrados.</p></div>
    @else
        @if(($identifier['valid'] ?? null) === false)<div class="alert alert-warning">{{ $identifier['message'] }} La consulta conserva el código que ingresaste.</div>@endif
        @if(!$found)
            <div class="postal-empty"><i class="fas fa-search" aria-hidden="true"></i><h2>No hay datos disponibles en esta consulta</h2><p>Revisa el código y el estado de cada fuente. Una conexión no disponible no significa que el paquete no exista.</p></div>
        @else
            <section class="postal-overview">
                <div><span class="postal-eyebrow">EXPEDIENTE DEL ENVÍO</span><h2>{{ $ipsPackage->MAILITM_FID ?? $cdsPackage->MAIL_OBJECT_ID ?? $code }}</h2><p>{{ $identifier['type'] }} · Consulta de los registros disponibles en cada fuente</p></div>
                <div class="postal-actions"><a class="btn btn-light" href="{{ route('postal.package.csv', ['codigo'=>$code]) }}"><i class="fas fa-file-csv"></i> Descargar expediente</a><a target="_blank" rel="noopener" class="btn btn-light" href="{{ route('postal.document', ['kind'=>'marbete','codigo'=>$code]) }}"><i class="fas fa-barcode"></i> Marbete interno</a>@if($declarations)<a target="_blank" rel="noopener" class="btn btn-light" href="{{ route('postal.document', ['kind'=>'aduana','codigo'=>$code]) }}"><i class="fas fa-print"></i> Resumen aduanero</a>@endif</div>
            </section>
            <section class="postal-panel postal-operational-summary" aria-label="Resumen para operaciones">
                <div class="postal-section-heading"><h2><i class="fas fa-clipboard-check"></i> Resumen para operaciones</h2><span>Datos recibidos de los sistemas fuente</span></div>
                <div class="postal-operations-metrics">
                    @if($section !== 'cds')<div><strong>{{ $operationsMetrics['movement_count'] }}</strong><span>movimientos IPS</span></div><div><strong>{{ $operationsMetrics['delivery_count'] }}</strong><span>registros de entrega</span></div><div><strong>{{ $operationsMetrics['international_count'] }}</strong><span>mensajes internacionales</span></div><div><strong>{{ $operationsMetrics['bag_count'] }}</strong><span>sacas vinculadas</span></div><div><strong>{{ $operationsMetrics['manifest_count'] }}</strong><span>manifiestos y formularios</span></div>@endif
                    @if($section !== 'ips')<div><strong>{{ count($declarations) }}</strong><span>declaraciones CDS</span></div><div><strong>{{ count($responses) }}</strong><span>respuestas aduaneras</span></div>@endif
                    <div><strong>{{ $operationsMetrics['content_count'] }}</strong><span>artículos declarados encontrados</span></div>
                </div>
                @if($section !== 'cds')
                    @if($operationalStatus['latest_event'])<p class="postal-note mb-2"><strong>Último movimiento de IPS:</strong> {{ $operationalStatus['latest_event']->EVENT_TYPE_NM_ES ?? 'Movimiento sin descripción' }} · {{ $operationalStatus['latest_event']->EVENT_GMT_DT }} GMT · {{ $operationalStatus['latest_event']->OFFICE_NM ?? $operationalStatus['latest_event']->OFFICE_FCD ?? 'oficina no informada' }}. Este es el último registro consultado, no una confirmación de ubicación física actual.</p>@else<p class="postal-note mb-2">IPS no devolvió movimientos para este código.</p>@endif
                    @if($operationalStatus['stale'])<div class="alert alert-warning mb-2"><i class="fas fa-clock"></i> El último movimiento tiene {{ $operationalStatus['age_days'] }} días. Supera el umbral orientativo de {{ $operationalStatus['stale_after_days'] }} días; confirma el caso con la oficina. No es un plazo oficial de entrega.</div>@endif
                    @if($operationalStatus['has_non_delivery_reason'])<div class="alert alert-warning mb-2"><i class="fas fa-truck"></i> IPS registra un motivo relacionado con una entrega no realizada. Revisa el detalle del intento antes de decidir el siguiente paso.</div>@endif
                    @if($operationsMetrics['bag_count'] === 0)<p class="postal-note mb-0">No se encontró un vínculo a saca o despacho en los registros consultados. Esto no confirma por sí solo una incidencia.</p>@endif
                @endif
            </section>
            <nav class="postal-tabs" aria-label="Secciones del expediente"><a href="#shipment"><i class="fas fa-box"></i> Paquete</a>@if($section !== 'cds')<a href="#movements"><i class="fas fa-route"></i> Movimientos <span>{{ $events->count() }}</span></a><a href="#delivery-records"><i class="fas fa-truck"></i> Entrega <span>{{ $deliveryRows->count() }}</span></a><a href="#international"><i class="fas fa-globe"></i> Intercambio internacional <span>{{ $ediRows->count() }}</span></a><a href="#declared-content"><i class="fas fa-box-open"></i> Contenido declarado</a><a href="#documents"><i class="fas fa-file-alt"></i> Despachos y formularios</a>@endif @if($section !== 'ips')<a href="#customs"><i class="fas fa-clipboard-list"></i> Aduana <span>{{ count($declarations) }}</span></a><a href="#responsibles"><i class="fas fa-user-check"></i> Responsables CDS</a>@endif</nav>
            <section id="shipment" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-box"></i> Datos del paquete</h2><span>{{ $sectionTitle }}</span></div>
                @if($ipsPackage && !empty($ipsPackage->EVT_TYPE_NM_ES))<div class="postal-current"><span class="postal-eyebrow">ÚLTIMO MOVIMIENTO INFORMADO POR IPS</span><strong>{{ $ipsPackage->EVT_TYPE_NM_ES }}</strong><small>{{ $ipsPackage->EVT_GMT_DT ?? '' }} · {{ $ipsPackage->EVT_OFFICE_NM ?? 'Oficina no informada' }}</small></div>@endif
                @if($section !== 'cds')<div class="postal-facts">
                    <div><span>Origen registrado en IPS</span><strong>{{ $ipsPackage->ORIG_COUNTRY_NM ?? 'No registrado' }}</strong></div>
                    <div><span>Destino registrado en IPS</span><strong>{{ $ipsPackage->DEST_COUNTRY_NM ?? 'No registrado' }}</strong></div>
                    <div><span>Peso en IPS</span><strong>{{ isset($ipsPackage->MAILITM_WEIGHT) ? $ipsPackage->MAILITM_WEIGHT.' kg' : 'No registrado' }}</strong></div>
                    <div><span>Clase postal</span><strong>{{ $ipsPackage->MAIL_CLASS_NM ?? $ipsPackage->MAIL_CLASS_CD ?? 'No registrada' }}</strong></div>
                </div>@endif
                @if($section !== 'ips' && $cdsPackage)<div class="postal-note"><strong>Registro CDS:</strong> {{ $cdsPackage->MAIL_OBJECT_ID }} · {{ $cdsPackage->MAIL_OBJECT_TYPE_CD ?? 'Tipo de pieza no informado' }} · Estado aduanero: {{ $cdsPackage->MAIL_STATE_NM ?: 'No descrito' }}</div>@endif
                @if($cdsPackage)<p class="postal-note">Estado del registro CDS: <strong>{{ $cdsPackage->MAIL_STATE_NM ?: 'Sin descripción' }}</strong>. Este estado aduanero no confirma una entrega al destinatario.</p>@endif
                @if(count($cds['packages'] ?? []) > 1)<div class="alert alert-warning">CDS devolvió varios registros para este identificador. Revisa los identificadores de cada declaración antes de usar los documentos.</div>@endif
                <div class="postal-contact-grid">@foreach(($ips['customerRows'] ?? []) as $person)<article><span class="postal-eyebrow">{{ ($person->SENDER_PAYEE_IND ?? '') === 'S' ? 'REMITENTE' : 'CONTACTO REGISTRADO' }}</span><h3>{{ trim(($person->CUSTOMER_FORENAME ?? '').' '.($person->CUSTOMER_NAME ?? '')) ?: 'Nombre no registrado' }}</h3><p>{{ $person->CUSTOMER_ADDRESS ?? '' }} {{ $person->CUSTOMER_CITY ?? '' }}</p><p>{{ $person->CUSTOMER_PHONE_NO ?? 'Teléfono no registrado' }}</p></article>@endforeach</div>
            </section>
            @if($section !== 'cds')<section id="movements" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-route"></i> Historial IPS</h2><span>Más reciente primero</span></div><p class="postal-note">Cada movimiento conserva la descripción del sistema de origen. El responsable corresponde al registro del evento.</p>
                @if($events->isNotEmpty())<div class="mb-3"><label for="event-filter">Buscar en el historial</label><input class="form-control" id="event-filter" type="search" placeholder="Evento, fecha, oficina o responsable" aria-controls="postal-timeline"><small id="event-filter-count" role="status" aria-live="polite"></small></div>@endif
                <div class="postal-timeline" id="postal-timeline">@forelse($events as $event)<article class="postal-event"><div class="postal-event-date"><time>{{ $event->EVENT_GMT_DT ?? 'Sin fecha' }}</time><small>Fecha registrada · IPS</small></div><div><span class="postal-source">{{ $event->SOURCE_DB ?? 'IPS' }} · {{ $event->EVENT_TYPE_CD ?? '—' }}</span><h3>{{ $event->EVENT_TYPE_NM_ES ?? 'Movimiento sin descripción' }}</h3><p><i class="fas fa-map-marker-alt"></i> {{ $event->OFFICE_NM ?? $event->OFFICE_FCD ?? 'Lugar no registrado' }}</p><p class="postal-note"><i class="fas fa-user"></i> {{ $event->USER_NM ?? $event->USER_FID ?? 'Responsable no informado por la fuente' }}</p>@if($event->NEXT_OFFICE_FCD ?? $event->NEXT_OFFICE_NM ?? false)<p><i class="fas fa-arrow-right"></i> Siguiente oficina: {{ trim(($event->NEXT_OFFICE_FCD ?? '').' '.($event->NEXT_OFFICE_NM ?? '')) }}</p>@endif @if(!empty($event->RETENTION_REASON_CD) || !empty($event->CONDITION_TXT) || !empty($event->ATTEMPTED_DELIVERY_LOCATION))<details><summary>Otros datos guardados por IPS</summary>@if(!empty($event->RETENTION_REASON_CD))<p>Motivo de retención (código IPS): {{ $event->RETENTION_REASON_CD }}</p>@endif @if(!empty($event->CONDITION_TXT))<p>Condición registrada: {{ $event->CONDITION_TXT }}</p>@endif @if(!empty($event->ATTEMPTED_DELIVERY_LOCATION))<p>Lugar del intento de entrega: {{ $event->ATTEMPTED_DELIVERY_LOCATION }}</p>@endif</details>@endif @if(!empty($event->DETAIL_TXT))<details><summary>Detalle del registro</summary><p>{{ $event->DETAIL_TXT }}</p></details>@endif</div></article>@empty<p class="postal-note">No hay movimientos IPS disponibles para mostrar.</p>@endforelse</div>
            </section>@endif
            @if($section !== 'cds')
                <section id="delivery-records" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-truck"></i> Intentos y constancias de entrega</h2><span>{{ $deliveryRows->count() }} registros de IPS</span></div>
                    <p class="postal-note">Estos son datos que IPS guardó para la entrega. Si un motivo aparece solo como código, se muestra como tal para no inventar su significado.</p>
                    <div class="table-responsive"><table class="table"><thead><tr><th>Fecha</th><th>Movimiento</th><th>Resultado / motivo (código)</th><th>Persona que recibió</th><th>Lugar registrado</th></tr></thead><tbody>
                    @forelse($deliveryRows as $delivery)<tr><td>{{ $delivery->EVENT_GMT_DT ?? 'Fecha no informada' }}</td><td>{{ $delivery->EVENT_TYPE_NM_ES ?? 'Movimiento de entrega' }}</td><td>@if($delivery->NON_DELIVERY_REASON_CD)No se completó la entrega · código {{ $delivery->NON_DELIVERY_REASON_CD }}@elseif($delivery->NON_DELIVERY_MEASURE_CD)Acción registrada · código {{ $delivery->NON_DELIVERY_MEASURE_CD }}@else IPS no informó un motivo de no entrega @endif</td><td>{{ $delivery->SIGNATORY_NM ?: 'No informado por IPS' }}</td><td>{{ trim(($delivery->DELIV_LOCATION ?? '').' '.($delivery->DELIV_POSTCODE ?? '')) ?: 'No informado por IPS' }}</td></tr>
                    @empty<tr><td colspan="5">IPS no devolvió constancias o intentos de entrega para este paquete.</td></tr>@endforelse
                    </tbody></table></div>
                </section>
                <section id="international" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-globe"></i> Mensajes internacionales (EDI)</h2><span>{{ $ediRows->count() }} registros recibidos</span></div>
                    <p class="postal-note">EDI son mensajes que se intercambian entre operadores postales. Un mensaje puede llegar antes que un escaneo local; por eso se conserva su fecha y ubicación como los informó IPS.</p>
                    <div class="table-responsive"><table class="table"><thead><tr><th>Fecha del evento</th><th>Mensaje postal</th><th>Ubicación informada</th><th>Operador remitente</th><th>Número de despacho</th></tr></thead><tbody>
                    @forelse($ediRows as $edi)<tr><td>{{ $edi->EVENT_LOCAL_DT ?: $edi->CAPTURE_GMT_DT ?: 'Fecha no informada' }}</td><td>{{ $edi->EVENT_TYPE_NM_ES ?: 'Mensaje sin descripción de catálogo' }}<small class="d-block text-muted">Código: {{ $edi->EVENT_TYPE_CD ?? 'No informado' }}</small></td><td>{{ $edi->LOCATION_ID ?? 'No informado' }}</td><td>{{ $edi->SENDER_ID ?: 'No informado' }}</td><td>{{ $edi->DESPATCH_NUMBER ?: 'No informado' }}</td></tr>
                    @empty<tr><td colspan="5">No hay mensajes internacionales asociados a este paquete.</td></tr>@endforelse
                    </tbody></table></div>
                </section>
                <section id="declared-content" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-box-open"></i> Contenido y datos de Aduana registrados en IPS</h2><span>{{ $contentPieceRows->count() }} artículos · {{ $customsRows->count() }} fichas</span></div>
                    <p class="postal-note">Estos datos son declaraciones guardadas en IPS; no equivalen a una inspección física ni a una decisión de Aduana.</p>
                    @forelse($customsRows as $customs)<div class="postal-facts"><div><span>Peso bruto declarado</span><strong>{{ $customs->DECLARED_GROSS_WEIGHT ?? 'No informado' }}</strong></div><div><span>Referencia aduanera del remitente</span><strong>{{ $customs->SENDER_CUSTOMS_REFERENCE_NO ?: 'No informada' }}</strong></div><div><span>Referencia aduanera del destinatario</span><strong>{{ $customs->RECIPIENT_CUSTOMS_REFERENCE_NO ?: 'No informada' }}</strong></div></div>@empty<p class="postal-note">IPS no devolvió una ficha de datos aduaneros para este paquete.</p>@endforelse
                    <div class="table-responsive"><table class="table"><thead><tr><th>Artículo declarado</th><th>Unidades</th><th>Valor</th><th>Peso neto</th><th>Origen / partida</th></tr></thead><tbody>@forelse($contentPieceRows as $piece)<tr><td>{{ $piece->DESCRIPTION ?: $piece->IDENTIFIER ?: 'Sin descripción' }}</td><td>{{ $piece->NUMBER_OF_UNITS ?? 'No informado' }}</td><td>{{ $piece->DECLARED_VALUE ?? 'No informado' }} {{ $piece->DECLARED_VALUE_CURRENCY_CD ?? '' }}</td><td>{{ $piece->NET_WEIGHT ?? 'No informado' }}</td><td>{{ $piece->ORIGIN_LOCATION ?: 'No informado' }}@if($piece->TARIFF_HEADING)<small class="d-block text-muted">Partida arancelaria: {{ $piece->TARIFF_HEADING }}</small>@endif</td></tr>@empty<tr><td colspan="5">No hay artículos desglosados en los datos aduaneros de IPS.</td></tr>@endforelse</tbody></table></div>
                </section>
            @endif
            @if($section !== 'ips')<section id="customs" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-clipboard-list"></i> Declaraciones y respuestas de Aduana</h2><span>CDS</span></div>
                @if($cds['truncated'] ?? false)<div class="alert alert-warning">El resultado supera el límite de consulta. Se muestra una parte de los registros.</div>@endif
                @forelse($declarations as $declaration)
                    @include('postal.declaration', ['declaration'=>$declaration])
                @empty<p class="postal-note">{{ $sources['CDS'] === 'empty' ? 'CDS no tiene una declaración asociada a este código.' : 'No hay declaraciones disponibles en esta consulta. Revisa el estado de la conexión CDS.' }}</p>@endforelse
                @foreach($responses as $response)<article class="postal-response"><span class="postal-eyebrow">RESPUESTA DE ADUANA</span><h3>{{ $response['decision'] ?: 'Decisión sin descripción en el catálogo' }}</h3><p>{{ $response['data']['fields']['DecisReasNm'] ?? 'Motivo no informado' }}</p><p>Estado del registro: {{ $response['state'] ?? 'No registrado' }}</p><small>Respuesta {{ $response['id'] }} · Paquete interno {{ $response['package_id'] }}</small>@if($response['data']['status'] === 'invalid')<p class="text-warning">El contenido no pudo interpretarse.</p>@endif</article>@endforeach
            </section>@endif
            @if($section !== 'cds')<section id="documents" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-file-alt"></i> Despachos, sacas y formularios</h2><span>IPS</span></div>
                <div class="table-responsive"><table class="table"><thead><tr><th>Saca / receptáculo</th><th>Despacho</th><th>Desde</th><th>Hacia</th><th>Salida registrada</th></tr></thead><tbody>@forelse(($ips['logisticRows'] ?? []) as $row)<tr><td>{{ $row->RECPTCL_FID ?? '—' }}</td><td>{{ $row->DESPTCH_FID ?? '—' }}</td><td>{{ $row->ORIG_OFFICE_FCD ?? '—' }}</td><td>{{ $row->DEST_OFFICE_FCD ?? '—' }}</td><td>{{ $row->DESPTCH_DEPARTURE_DT ?? '—' }}</td></tr>@empty<tr><td colspan="5">Sin despachos asociados disponibles.</td></tr>@endforelse</tbody></table></div>
                <h3>Formularios y manifiestos registrados</h3><p class="postal-note">Se muestra el nombre registrado en IPS, incluidos los formularios CN cuando la fuente los identifica.</p>
                <div class="table-responsive"><table class="table"><thead><tr><th>Identificador</th><th>Formulario</th><th>Fecha local</th><th>Oficina</th><th>Responsable</th></tr></thead><tbody>@forelse(($ips['manifestRows'] ?? []) as $row)<tr><td>{{ $row->MANIFEST_LIST_ID }}</td><td>{{ $row->FORM_NM ?? $row->MANIF_TYPE_ID ?? 'No informado' }}</td><td>{{ $row->CREATION_LCL_DT ?? '—' }}</td><td>{{ $row->OFFICE_NM ?? '—' }}</td><td>{{ $row->USER_NM ?? $row->USER_FID ?? 'No informado' }}</td></tr>@empty<tr><td colspan="5">Sin formularios asociados disponibles.</td></tr>@endforelse</tbody></table></div>
                @can('ips.read')<a href="{{ route('sqlserver.datos', ['codigo'=>$code]) }}" class="btn btn-outline-primary"><i class="fas fa-database"></i> Ver detalle técnico de IPS</a>@endcan
            </section>@endif
            @if($section !== 'ips')<section id="responsibles" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-user-check"></i> Quién registró los cambios en CDS</h2><span>Fechas UTC</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Fecha (UTC)</th><th>Acción registrada</th><th>Responsable</th><th>Oficina</th><th>Documento vinculado</th></tr></thead><tbody>@forelse(collect($cds['events'] ?? [])->sortByDesc('occurred_at') as $event)<tr><td>{{ $event['occurred_at'] }}</td><td>{{ $event['name'] ?? $event['code'] }}</td><td>{{ $event['user_name'] ?? $event['user_code'] ?? 'No informado' }}</td><td>{{ $event['office'] ?? 'No informada' }}</td><td><small>{{ $event['kind'] === 'declarations' ? 'Declaración' : 'Respuesta' }} {{ $event['record_id'] }}</small></td></tr>@empty<tr><td colspan="5">Sin eventos CDS disponibles.</td></tr>@endforelse</tbody></table></div></section>@endif
        @endif
    @endif
</div>
@include('footer')
@stop
@section('css')<link rel="stylesheet" href="{{ asset('css/postal-workspace.css') }}"><link rel="stylesheet" href="{{ asset('css/postal-operations.css') }}">@stop
@section('js')<script src="{{ asset('js/postal-workspace.js') }}" defer></script>@stop
