@extends('adminlte::page')
@section('title','Buscar marbetes y sacas IPS | SITRA')
@section('content_header')
<div class="postal-heading"><div><span class="postal-eyebrow">IPS · LOGÍSTICA POSTAL</span><h1>Buscar marbetes y sacas</h1><p>Consulta qué saca identifica este marbete, dónde aparece en su recorrido y qué paquetes se asociaron.</p></div></div>
@stop
@section('content')
<div class="postal-workspace">
    @include('postal.sections')
    <form class="postal-search" action="{{ route('postal.receptacles') }}" method="get">
        <label for="marbete-code">Número de marbete, registro o seguro</label>
        <div class="postal-search-row"><i class="fas fa-barcode" aria-hidden="true"></i><input id="marbete-code" name="marbete" value="{{ $identifier }}" maxlength="80" required autocomplete="off" placeholder="Escanea el código completo, por ejemplo BEBRUABOLPBBAEN60073003000227"><button class="btn btn-primary"><i class="fas fa-search"></i> Buscar marbete</button></div>
        <p class="postal-note mb-0">Busca el número completo guardado en IPS. Un marbete identifica una saca o receptáculo, que puede contener varios envíos.</p>
    </form>
    @if($error)<div class="alert alert-danger" role="alert">{{ $error }}</div>@endif
    @if($result)
        @if($result['receptacles'])
            @if(count($result['receptacles']) === 1)
                @php($bag = $result['receptacles'][0])
                <section class="postal-overview"><div><span class="postal-eyebrow">MARBETE / SACO ENCONTRADO EN IPS</span><h2>{{ $bag->RECPTCL_FID ?: $identifier }}</h2><p>Identificador del receptáculo asociado a tus paquetes en el registro IPS.</p></div><div class="postal-bag-total"><strong>{{ count($result['items']) }}</strong><span>paquetes<br>asociados</span></div></section>
                <div class="postal-facts postal-panel"><div><span>Peso registrado</span><strong>{{ $bag->RECPTCL_WEIGHT !== null ? number_format((float)$bag->RECPTCL_WEIGHT,3,',','.').' kg' : 'No informado' }}</strong></div><div><span>Paquetes en IPS</span><strong>{{ $bag->RECPTCL_MAILITMS_NO ?? count($result['items']) }}</strong></div><div><span>Número de seguro</span><strong>{{ $bag->RECPTCL_SEAL_NUMBER ?: 'No registrado' }}</strong></div><div><span>Subclase postal</span><strong>{{ $bag->MAIL_SUBCLASS_FCD ?: 'No informada' }}</strong></div><div><span>Registro alternativo</span><strong>{{ $bag->RECPTCL_REG_NO ?: 'No registrado' }}</strong></div><div><span>Seguro alternativo</span><strong>{{ $bag->RECPTCL_INS_NO ?: 'No registrado' }}</strong></div></div>
                <section class="postal-panel postal-reconciliation"><div class="postal-section-heading"><h2><i class="fas fa-balance-scale"></i> Revisión rápida de la saca</h2><span>Comparación de registros IPS</span></div>
                    @if($reconciliation['count_matches'] === true)<div class="postal-check is-ok"><i class="fas fa-check-circle"></i><span>La cantidad coincide: IPS declara {{ $reconciliation['declared_count'] }} paquetes y se encontraron {{ $reconciliation['linked_count'] }} relacionados.</span></div>
                    @elseif($reconciliation['count_matches'] === false)<div class="postal-check is-warning"><i class="fas fa-exclamation-triangle"></i><span>La cantidad no coincide: IPS declara {{ $reconciliation['declared_count'] }} paquetes, pero los eventos consultados relacionan {{ $reconciliation['linked_count'] }}. Conviene revisar la saca en IPS.</span></div>
                    @else<div class="postal-check is-neutral"><i class="fas fa-info-circle"></i><span>No se puede confirmar la cantidad: falta el total declarado o IPS indicó que hay más registros de los mostrados.</span></div>@endif
                    <div class="postal-reconciliation-weights"><div><span>Peso registrado de la saca</span><strong>{{ $reconciliation['bag_weight'] !== null ? number_format($reconciliation['bag_weight'],3,',','.').' kg' : 'No informado' }}</strong></div><div><span>Suma de pesos individuales con dato</span><strong>{{ number_format($reconciliation['item_weight_total'],3,',','.') }} kg</strong><small>{{ $reconciliation['items_without_weight'] }} paquete(s) sin peso registrado</small></div></div>
                    <p class="postal-note mb-0">Los pesos se muestran como referencia: el peso de la saca puede incluir embalaje y los registros individuales pueden usar criterios distintos. La comparación de cantidad solo cuenta vínculos de paquetes registrados en los eventos IPS.</p>
                </section>
                @if($bag->COMMENTS)<section class="postal-panel"><h2><i class="fas fa-comment-alt"></i> Observación guardada</h2><p>{{ $bag->COMMENTS }}</p></section>@endif
                <div class="postal-actions postal-bag-actions"><a class="btn btn-outline-primary" target="_blank" rel="noopener" href="{{ route('postal.receptacles.document',['type'=>'etiqueta','marbete'=>$identifier]) }}"><i class="fas fa-print"></i> Imprimir etiqueta interna</a><a class="btn btn-outline-primary" href="{{ route('postal.receptacles.document',['type'=>'csv','marbete'=>$identifier]) }}"><i class="fas fa-file-csv"></i> Descargar paquetes CSV</a></div>
                <nav class="postal-tabs" aria-label="Secciones del resultado"><a href="#bag-events"><i class="fas fa-history"></i> Eventos ({{ count($result['events']) }})</a><a href="#bag-dispatch"><i class="fas fa-plane-departure"></i> Despacho</a><a href="#bag-items"><i class="fas fa-boxes"></i> Paquetes ({{ count($result['items']) }})</a><a href="#bag-forms"><i class="fas fa-file-alt"></i> Formularios</a></nav>
                @if($result['truncated'])<div class="alert alert-warning">La saca tiene más información que el límite visible. Se muestran los registros disponibles hasta ese límite.</div>@endif
                <section id="bag-events" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-history"></i> Historial de la saca</h2><span>Hora guardada en IPS</span></div>
                    <div class="postal-timeline">@forelse($result['events'] as $event)<article class="postal-event"><div class="postal-event-date">{{ $event->EVENT_GMT_DT ?? 'Fecha no registrada' }}<small>Hora registrada por IPS</small></div><div><span class="postal-source">Evento IPS · {{ $event->EVENT_TYPE_CD }}</span><h3>{{ $event->EVENT_NAME_ES ?: $event->EVENT_NAME ?: 'Evento sin descripción en catálogo' }}</h3><p><i class="fas fa-map-marker-alt"></i> {{ $event->OFFICE_NM ?: $event->OFFICE_FCD ?: 'Oficina no registrada' }}</p><p><i class="fas fa-user"></i> {{ $event->USER_NM ?: $event->USER_FID ?: 'IPS no registró al usuario' }}</p>@if($event->NEXT_OFFICE_CD)<p><i class="fas fa-arrow-right"></i> Siguiente oficina (código IPS): {{ $event->NEXT_OFFICE_CD }}</p>@endif</div></article>@empty<p class="postal-note">El marbete existe, pero IPS aún no tiene eventos de recorrido asociados.</p>@endforelse</div>
                </section>
                <section id="bag-dispatch" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-plane-departure"></i> Despacho que contiene la saca</h2><span>Datos de IPS</span></div>
                    @if($bag->DESPTCH_PID)<div class="postal-facts"><div><span>Número de despacho</span><strong>{{ $bag->DESPTCH_FID ?: 'No informado' }}</strong></div><div><span>Desde oficina</span><strong>{{ $bag->ORIG_OFFICE_FCD ?: 'No informada' }}</strong></div><div><span>Hacia oficina</span><strong>{{ $bag->DEST_OFFICE_FCD ?: 'No informada' }}</strong></div><div><span>Fecha de salida</span><strong>{{ $bag->DESPTCH_DEPARTURE_DT ?: 'No registrada' }}</strong></div><div><span>Sacas declaradas en el despacho</span><strong>{{ $bag->DESPTCH_RECPTCLS_NO ?? 'No informadas' }}</strong></div><div><span>Peso del despacho</span><strong>{{ $bag->DESPTCH_WEIGHT !== null ? number_format((float)$bag->DESPTCH_WEIGHT,3,',','.').' kg' : 'No informado' }}</strong></div></div>@else<div class="postal-empty postal-empty-compact"><i class="fas fa-inbox"></i><h3>Esta saca todavía no está vinculada a un despacho</h3><p>IPS no tiene un DESPTCH_PID asociado a este receptáculo.</p></div>@endif
                </section>
                <section id="bag-items" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-boxes"></i> Paquetes relacionados</h2><span>{{ count($result['items']) }} listados</span></div><p class="postal-note">La relación se obtiene de los eventos IPS que guardan el identificador de esta saca. Abre un paquete para ver su historial.</p>
                    <div class="table-responsive"><table class="table"><thead><tr><th>Código del envío</th><th>Clase</th><th>Origen</th><th>Destino</th><th>Último movimiento registrado</th><th>Fecha</th><th></th></tr></thead><tbody>
                    @forelse($result['items'] as $item)<tr><td><strong>{{ $item->MAILITM_FID ?: 'Identificador local' }}</strong>@if($item->MAILITM_LOCAL_ID)<small class="d-block text-muted">Local: {{ $item->MAILITM_LOCAL_ID }}</small>@endif</td><td>{{ $item->MAIL_CLASS_NAME ?: $item->MAIL_CLASS_CD ?: '—' }}</td><td>{{ $item->ORIGIN_COUNTRY ?: '—' }}</td><td>{{ $item->DEST_COUNTRY ?: '—' }}</td><td>{{ $item->EVENT_NAME_ES ?: $item->EVENT_NAME ?: 'Movimiento no descrito' }} · {{ $item->POSTAL_STATUS_NAME ?: 'Estado no descrito' }}</td><td>{{ $item->EVT_GMT_DT ?: '—' }}</td><td>@if($item->MAILITM_FID)<a class="btn btn-sm btn-outline-primary" href="{{ route('postal.ips',['codigo'=>$item->MAILITM_FID]) }}"><i class="fas fa-search"></i> Abrir paquete</a>@endif</td></tr>@empty<tr><td colspan="7">No hay paquetes vinculados en los eventos IPS de esta saca.</td></tr>@endforelse
                    </tbody></table></div>
                </section>
                <section id="bag-forms" class="postal-panel"><div class="postal-section-heading"><h2><i class="fas fa-file-alt"></i> Manifiestos y formularios asociados</h2><span>Relacionados por los paquetes de la saca</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Número de manifiesto</th><th>Formulario registrado</th><th>Fecha local</th><th>Persona que lo registró</th><th>Observación</th></tr></thead><tbody>@forelse($result['manifests'] as $manifest)<tr><td>{{ $manifest->MANIFEST_LIST_ID }}</td><td>{{ $manifest->FORM_NM ?: $manifest->MANIF_TYPE_ID ?: 'Tipo no informado' }}</td><td>{{ $manifest->CREATION_LCL_DT ?: '—' }}</td><td>{{ $manifest->USER_NM ?: $manifest->USER_FID ?: 'IPS no informó al usuario' }}</td><td>{{ $manifest->OBSERVATION ?: 'Sin observaciones' }}</td></tr>@empty<tr><td colspan="5">No se encontraron manifiestos vinculados a los paquetes de esta saca.</td></tr>@endforelse</tbody></table></div></section>
            @else
                <section class="postal-panel"><h2>Hay varios registros que coinciden</h2><p>El número buscado aparece en varios receptáculos. Comprueba el tipo de identificador y vuelve a buscar el código completo.</p><div class="table-responsive"><table class="table"><thead><tr><th>Marbete</th><th>Número de registro</th><th>Seguro</th><th>Peso</th><th>Fecha</th></tr></thead><tbody>@foreach($result['receptacles'] as $bag)<tr><td>{{ $bag->RECPTCL_FID ?: '—' }}</td><td>{{ $bag->RECPTCL_REG_NO ?: '—' }}</td><td>{{ $bag->RECPTCL_INS_NO ?: '—' }}</td><td>{{ $bag->RECPTCL_WEIGHT ?? '—' }}</td><td>{{ $bag->EVT_GMT_DT ?? '—' }}</td></tr>@endforeach</tbody></table></div></section>
            @endif
        @else
            <div class="postal-empty"><i class="fas fa-search" aria-hidden="true"></i><h2>No encontramos ese marbete en IPS</h2><p>Verifica si copiaste el número completo. La búsqueda prueba marbete, registro y seguro, con el identificador guardado en IPS.</p><code>{{ $identifier }}</code></div>
        @endif
    @endif
</div>
@include('footer')
@stop
@section('css')<link rel="stylesheet" href="{{ asset('css/postal-workspace.css') }}"><link rel="stylesheet" href="{{ asset('css/postal-operations.css') }}">@stop
